---

hash: sha256
cipher: aes-cbc-essiv:sha256
key_file: disk_passphrase
key_file_dest: /root/.cryptsetup_passphrase_tmp
key_size: 256

volume_info:
  volume_group: "{{ docker_volume_group }}"
  logical_volume: "{{ docker_container_name }}"
  size: 10g
  mount_point: "/var/{{ docker_container_name }}"
  mapping: "{{ docker_volume_group }}-{{ docker_container_name }}"
  fstype: xfs
  is_encrypted: false
