---

galaxy_info:
  author: devops@aem.design
  description: remove logical volume
  company: AEM.Design
  license: Apache
  min_ansible_version: 2.0
  platforms:
  - name: Centos
    versions: 7
  categories: system
  dependencies: []
