---
galaxy_info:
  version: "1.0"
  author: devops@aem.design
  description: Deploy packages from Maven to Mulesoft ESB container
  company: AEM.Design
  license: Apache-2.0
  min_ansible_version: 2.0
  platforms:
  - name: Centos
    versions:
    - 7
  categories:
    - system
    - docker
    - configuration
    - maven
    - mule
    - esb
dependencies: []

