---
## file: site.yml
## This playbook deploys the whole application stack.

- name: site deploy
  hosts: all
#  pre_tasks:
#    - include_role:
#        name: aem_design.docker_available
#    - include_role:
#        name: aem_design.docker_login

#- include: playbooks/service/consul.yml
#- include: playbooks/service/registrator.yml

#- import_playbook: playbooks/service/nexus.yml
#- import_playbook: playbooks/service/jenkins.yml
- import_playbook: playbooks/service/author.yml
#- import_playbook: playbooks/service/publish.yml
#- import_playbook: playbooks/service/dispatcher-author.yml
#- import_playbook: playbooks/service/dispatcher-publish.yml
#- import_playbook: playbooks/service/selenium-grid.yml
#- import_playbook: playbooks/service/selenium-grid-node-chrome.yml
#- import_playbook: playbooks/service/selenium-grid-node-firefox.yml


###

#  docker run -d -P --name selenium-hub -e GRID_TIMEOUT=10 selenium/hub
#
#  docker run -d --link selenium-hub:hub selenium/node-chrome
#  docker run -d --link selenium-hub:hub selenium/node-firefox


### TODO: refactor following

#- include: playbooks/service/consul.yml
#- include: playbooks/service/registrator.yml
#- include: playbooks/service/solr.yml
#- include: playbooks/service/dispatcher.yml
#- include: playbooks/service/esb.yml

#- include: playbooks/management.yml
#- include: playbooks/service/security.yml
#- include: playbooks/service/cahost.yml
