#!/usr/bin/env bash

# shellcheck disable=SC2034
DIR_INC="$(cd .. && cd .. && pwd)/scripts"
# shellcheck disable=SC2034
DIR_ROOT="$(cd .. && cd .. && pwd)"

if [[ -d $DIR_INC ]]; then

    source $DIR_INC/functions.sh
    doPythonCheck

fi

CURRDIR="$(pwd)"
ANSIBLEPLAYBOOK=$(which ansible-playbook)
ANSIBLE=$(which ansible)
ANSIBLE_PLAYBOOK="site.yml"
ANSIBLE_INVENTORY="inventory/localdev.yml"
echo PARAMS="$@"
echo CURRDIR=$CURRDIR
cd $CURRDIR

if [[ -z $ANSIBLE ]]; then
    debug "Please activate your Python Virtual Environment."
    debug "You can a new virtual environment: ${PYTHON_ENV}" "info"
    exit 1
fi


$ANSIBLE --version
$ANSIBLEPLAYBOOK --version
if [[ "" == "$@" ]]; then
    echo $ANSIBLEPLAYBOOK -i $ANSIBLE_INVENTORY $ANSIBLE_PLAYBOOK
    $ANSIBLEPLAYBOOK -i $ANSIBLE_INVENTORY $ANSIBLE_PLAYBOOK
else
    echo $ANSIBLEPLAYBOOK -i $ANSIBLE_INVENTORY "$@" $ANSIBLE_PLAYBOOK
    $ANSIBLEPLAYBOOK -i $ANSIBLE_INVENTORY "$@" $ANSIBLE_PLAYBOOK
fi