---

- name: docker container remove
  docker_container:
    name: "{{ docker_container_name }}"
    state: absent
  become: yes

- name: checking mount point status
  check_mode: no
  ignore_errors: true
  stat:
    path: "{{ volume_info.mount_point }}"
  register: mount_status
  become: yes
  become_method: sudo

- name: unmount lvm volumes on boot
  mount:
    name: "{{ volume_info.mount_point }}"
    state: absent
  when: >
    mount_status.stat.exists and
    volume_info is defined
  become: yes
  become_method: sudo

- name: checking logical volume status
  check_mode: no
  ignore_errors: true
  stat:
    path: /dev/{{ volume_info.volume_group }}/{{ volume_info.logical_volume }}
  register: lv_stat
  become: yes
  become_method: sudo

- name: remove logical volume
  lvol:
    vg: "{{ volume_info.volume_group }}"
    lv: "{{ volume_info.logical_volume }}"
    state: absent
    force: yes
  when: >
    lv_stat.stat.exists
  become: yes
  become_method: sudo

- name: checking mapped volume status
  check_mode: no
  ignore_errors: true
  stat:
    path: /dev/mapper{{ volume_info.volume_group }}-{{ volume_info.logical_volume }}
  register: mapped_stat
  become: yes
  become_method: sudo

- name: unmount lvm volumes on boot
  mount:
    name: "{{ volume_info.mount_point }}"
    state: absent
  when: >
    mount_status.stat.exists and
    volume_info is defined
  become: yes
  become_method: sudo

- name: delete mount point directory
  file:
    path: "{{ volume_info.mount_point }}"
    state: absent
  when: >
      mount_status.stat.exists and
      volume_info is defined
  become: yes