---
- set_fact:
    role_file_source: "{{ role_path }}/files/docker/"
    role_comment: "( {{ docker_container_name | default('mule-esb') }} )"

- name: ensure container is started {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    published_ports: "{{ docker_published_ports }}"
    volumes: "{{ docker_volumes }}"
    docker_host: "{{ docker_host }}"
    env:
      TZ: "{{ docker_timezone }}"
  tags:
    - docker-container

- name: wait until service is ready {{ role_comment }}
  uri:
    url: "http://{{ service_muleesb_address }}:{{ muleesb_port }}"
    return_content: yes
    timeout: 300
  register: service_console
  until: service_console.content.find("Mule") != -1
  delay: "{{ wait_delay | default(5) }}"
  retries: 360
  tags:
    - docker-container
