---
- name: build jenkins service
  hosts: jenkins
  vars_files:
    - "{{inventory_dir}}/../group_vars/all/vars.yml"
    - "{{inventory_dir}}/../group_vars/jenkins/vars.yml"
  pre_tasks:
    - include_role:
        name: aem_design.docker_available
    - include_role:
        name: aem_design.docker_login
#    - include_role:
#        name: centos-tini
#    - include_role:
#        name: oracle-jdk
#    - include_role:
#        name: jenkins-base
  roles:
    - jenkins


