---

- name: selenium grid node chrome playbook
  hosts: selenium-grid-node-chrome
  vars_files:
    - "{{inventory_dir}}/../group_vars/all/vars.yml"
    - "{{inventory_dir}}/../group_vars/selenium-grid-node-chrome/vars.yml"

  pre_tasks:
    - include_role:
        name: aem_design.docker_available
    - include_role:
        name: aem_design.docker_login

  roles:
    - {
      role: selenium-grid-node,
      docker_image_name: "node-chrome",
    }
