---

- set_fact:
    role_file_source: "{{ role_path }}/files/docker/"
    role_comment: "( {{ docker_container_name | default('registrator') }} )"

- name: ensure container is started {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    published_ports: "{{ docker_published_ports }}"
    volumes: "{{ docker_volumes }}"
    docker_host: "{{ docker_host }}"
    env:
      TZ: "{{ docker_timezone }}"
      SERVICE_IGNORE: yes
  tags:
    - docker-container
