---

  - name: Add Allowed Authorized Keys
    lineinfile:
      dest: "{{ ssh.authorized_keys_dest }}"
      line: "{{ lookup('file', item ) }}"
      state: present
      create: yes
    with_lines: ls -1 roles/security-rotate-keys/files/allow/*.pub
    tags:
      - security-rotate-keys
      - add-allow-adminkeys

  - name: Remove Deny Authorized Keys
    lineinfile:
      dest: "{{ ssh.authorized_keys_dest }}"
      line: "{{ lookup('file', item ) }}"
      state: absent
      create: yes
    with_lines: ls -1 roles/security-rotate-keys/files/deny/*.pub
    tags:
      - security-rotate-keys
      - remove-deny-adminkeys
