---
# file: group_vars/consul-client

#docker_image: consul
#docker_image_tag: latest

consul_host: consul.service.dc1.consul

consul_config_path: /var/consul                            # Path to mount the volume to the host
consul_bind_ip: 192.168.27.2                               # IP to bind the consul container in the host

#docker_container_name: consul_client                       # Name of the docker container

consul_network_name: consul-net                            # Docker network to add DAM containers to

docker_ipam_options:
  subnet: '172.10.0.0/16'
  gateway: '172.10.0.1'
  iprange: '172.10.1.0/24'

#docker_volumes:
#  - "/var/consul/data:/consul/data:z"
